
CREATE TABLE GS_RATE (
	GS_RATE_ID INT AUTO_INCREMENT PRIMARY KEY,
    DATE VARCHAR(20),    
    GOLD_RATE VARCHAR(20), 
    SILVER_RATE VARCHAR(20)
);


ALTER TABLE AD_SALESDATA
ADD COLUMN BILL_TYPES VARCHAR(20);

ALTER TABLE AD_SALESDATA
ADD COLUMN OLD_BALANCE_AMOUNT VARCHAR(50);

COMMIT;