
ALTER TABLE AD_SALESDATA
ADD COLUMN DATE VARCHAR(20);

ALTER TABLE AD_SALESDATA
ADD COLUMN GOLD_RATE VARCHAR(20);

ALTER TABLE AD_SALESDATA
ADD COLUMN SILVER_RATE VARCHAR(20);

ALTER TABLE AD_SALESDATA
ADD COLUMN STATUS VARCHAR(10);

ALTER TABLE AD_SALESDATA
ADD COLUMN SALES_AMOUNT2 VARCHAR(50);

COMMIT;